version: '3.9'

services:

  grandy-db:
    container_name: grandy-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=grandy-db
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  grandy-api:
    container_name: grandy_api
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4004:4004
    restart: always
    depends_on:
      - grandy-db

volumes:
  pgdata:
