version: '3.9'

services:

  grandy-db:
    container_name: grandy-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=grandy-db
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5437:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: